# Generated by Django 4.1.6 on 2023-03-10 09:03

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('releasedate', models.DateField(blank=True, null=True)),
                ('image', models.CharField(blank=True, max_length=255, null=True)),
                ('photos', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(default='Lorem Ipsum')),
            ],
        ),
        migrations.CreateModel(
            name='SabiasQue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('curiosity', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Trail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('startDate', models.DateField()),
                ('finishDate', models.DateField()),
                ('maxPlayers', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('avatar', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=50)),
                ('plan', models.CharField(choices=[('PREMIUM', 'Premium'), ('STANDARD', 'Standard')], default='STANDARD', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='UserInTrail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gametrail.trail')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gametrail.user')),
            ],
        ),
        migrations.AddField(
            model_name='trail',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gametrail.user'),
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('type', models.CharField(choices=[('KINDNESS', 'Kindness'), ('FUNNY', 'Funny'), ('TEAMWORK', 'Teamwork'), ('ABILITY', 'Ability'), ('AVAILABILITY', 'Availability')], max_length=255)),
                ('ratedUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rate_recieved', to='gametrail.user')),
                ('userWhoRate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rate_made', to='gametrail.user')),
            ],
        ),
        migrations.CreateModel(
            name='Platform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(max_length=40)),
                ('game', models.ManyToManyField(to='gametrail.game')),
                ('trail', models.ManyToManyField(to='gametrail.trail')),
            ],
        ),
        migrations.CreateModel(
            name='MinRatingTrail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('minRating', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('ratingType', models.CharField(choices=[('KINDNESS', 'Kindness'), ('FUNNY', 'Funny'), ('TEAMWORK', 'Teamwork'), ('ABILITY', 'Ability'), ('AVAILABILITY', 'Availability')], max_length=50)),
                ('trail', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gametrail.trail')),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre', models.CharField(max_length=100)),
                ('game', models.ManyToManyField(to='gametrail.game')),
            ],
        ),
        migrations.CreateModel(
            name='GameList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='gametrail.user')),
            ],
        ),
        migrations.CreateModel(
            name='GameInTrail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('priority', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('status', models.CharField(choices=[('PLAYING', 'Playing'), ('PENDING', 'Pending'), ('FINISHED', 'Finished')], max_length=255)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gametrail.game')),
                ('trail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gametrail.trail')),
            ],
        ),
        migrations.CreateModel(
            name='GameInList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creationMoment', models.DateTimeField(default=django.utils.timezone.now)),
                ('lastModified', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('PLAYING', 'Playing'), ('PENDING', 'Pending'), ('FINISHED', 'Finished')], max_length=255)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gametrail.game')),
                ('gameList', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='games_in_list', to='gametrail.gamelist')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commentText', models.TextField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('game', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gametrail.game')),
                ('userCommented', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments_received', to='gametrail.user')),
                ('userWhoComments', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments_made', to='gametrail.user')),
            ],
        ),
        migrations.CreateModel(
            name='ChatTrail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chatText', models.TextField()),
                ('createdMoment', models.DateTimeField(default=django.utils.timezone.now)),
                ('trail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gametrail.trail')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gametrail.user')),
            ],
        ),
    ]
