# Generated by Django 4.1.6 on 2023-03-03 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=300)),
                ('image', models.CharField(max_length=200)),
                ('photos', models.CharField(max_length=400)),
                ('departureDate', models.DateField(null=True)),
                ('genres', models.CharField(choices=[('No definido', 'No definido'), ('ACTION', 'ACTION'), ('SPORT', 'SPORT'), ('ROL', 'ROL')], default='No definido', max_length=255)),
                ('platform', models.CharField(choices=[('No definido', 'No definido'), ('XBOX', 'XBOX'), ('PLAYSTATION', 'PLAYSTATION'), ('PC', 'PC')], default='No definido', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nameUser', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=300)),
                ('image', models.CharField(max_length=200)),
                ('password', models.CharField(max_length=200)),
                ('plan', models.CharField(choices=[('STANDARD', 'STANDARD'), ('PREMIUM', 'PREMIUM')], default='STANDARD', max_length=255)),
            ],
        ),
    ]
