# Generated by Django 4.1.6 on 2023-03-05 10:35

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('gametrail', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SabiasQue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('curiosity', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Trail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('startDate', models.DateField()),
                ('finishDate', models.DateField()),
                ('maxPlayers', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('avatar', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=50)),
                ('plan', models.CharField(choices=[('PREMIUM', 'Premium'), ('STANDARD', 'Standard')], default='STANDARD', max_length=10)),
            ],
        ),
        migrations.RenameField(
            model_name='game',
            old_name='title',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='game',
            name='img',
        ),
        migrations.AddField(
            model_name='game',
            name='description',
            field=models.TextField(default='Lorem Ipsum'),
        ),
        migrations.AddField(
            model_name='game',
            name='image',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='game',
            name='photos',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='game',
            name='releaseDate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='UserInTrail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gametrail.trail')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gametrail.user')),
            ],
        ),
        migrations.AddField(
            model_name='trail',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gametrail.user'),
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField()),
                ('type', models.CharField(choices=[('KINDNESS', 'Kindness'), ('FUNNY', 'Funny'), ('TEAMWORK', 'Teamwork'), ('ABILITY', 'Ability'), ('AVAILABILITY', 'Availability')], max_length=255)),
                ('ratedUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rate_recieved', to='gametrail.user')),
                ('userWhoRate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rate_made', to='gametrail.user')),
            ],
        ),
        migrations.CreateModel(
            name='Platform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(max_length=40)),
                ('game', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gametrail.game')),
                ('trail', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gametrail.trail')),
            ],
        ),
        migrations.CreateModel(
            name='MinRatingTrail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('minRating', models.IntegerField()),
                ('ratingType', models.CharField(choices=[('KINDNESS', 'Kindness'), ('FUNNY', 'Funny'), ('TEAMWORK', 'Teamwork'), ('ABILITY', 'Ability'), ('AVAILABILITY', 'Availability')], max_length=50)),
                ('trail', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gametrail.trail')),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre', models.CharField(max_length=100)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='genres', to='gametrail.game')),
            ],
        ),
        migrations.CreateModel(
            name='GameList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='gametrail.user')),
            ],
        ),
        migrations.CreateModel(
            name='GameInList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creationMoment', models.DateTimeField(default=django.utils.timezone.now)),
                ('lastModified', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('PLAYING', 'Playing'), ('PENDING', 'Pending'), ('FINISHED', 'Finished')], max_length=255)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gametrail.game')),
                ('gameList', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='games_in_list', to='gametrail.gamelist')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commentText', models.TextField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('game', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gametrail.game')),
                ('userCommented', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments_received', to='gametrail.user')),
                ('userWhoComments', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments_made', to='gametrail.user')),
            ],
        ),
        migrations.CreateModel(
            name='ChatTrail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chatText', models.TextField()),
                ('createdMoment', models.DateTimeField(default=django.utils.timezone.now)),
                ('trail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gametrail.trail')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gametrail.user')),
            ],
        ),
    ]
