# Generated by Django 4.1.6 on 2023-03-06 09:44

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gametrail', '0002_sabiasque_trail_user_rename_title_game_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='minratingtrail',
            name='minRating',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='rating',
            name='rating',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='trail',
            name='maxPlayers',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.CreateModel(
            name='GameInTrail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('priority', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('status', models.CharField(choices=[('PLAYING', 'Playing'), ('PENDING', 'Pending'), ('FINISHED', 'Finished')], max_length=255)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gametrail.game')),
                ('trail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gametrail.trail')),
            ],
        ),
    ]
