# Generated by Django 4.1.6 on 2023-03-07 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gametrail', '0003_alter_minratingtrail_minrating_alter_rating_rating_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='genre',
            name='game',
        ),
        migrations.RemoveField(
            model_name='platform',
            name='game',
        ),
        migrations.RemoveField(
            model_name='platform',
            name='trail',
        ),
        migrations.AddField(
            model_name='genre',
            name='game',
            field=models.ManyToManyField(to='gametrail.game'),
        ),
        migrations.AddField(
            model_name='platform',
            name='game',
            field=models.ManyToManyField(blank=True, null=True, to='gametrail.game'),
        ),
        migrations.AddField(
            model_name='platform',
            name='trail',
            field=models.ManyToManyField(blank=True, null=True, to='gametrail.trail'),
        ),
    ]
